# See the configuration reference at https://symfony.com/bundles/SchebTwoFactorBundle/6.x/configuration.html
scheb_two_factor:
    email:
        digits: 6
        enabled: true
        sender_email: no-reply@example.com
        template: 'security/2fa_form.html.twig'
        mailer: App\Infrastructure\Mailer\TwoFactorMailer
